services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    command: celery -A app.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_flower:
    build: .
    command: celery -A app.celery_app flower
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis

  task_adder:
    build: .
    volumes:
      - .:/app
    command: python add_task.py
    depends_on:
      - redis
      - celery_worker
      - celery_beat
    stdin_open: true
    tty: true

  task_viewer:
    build: .
    volumes:
      - .:/app
    command: python view_tasks.py
    depends_on:
      - redis